### ISSUE TITLE
fix nomad UI skin

### ISSUE THREAD

**Issue by CookieNoob** [CookieNoob/nomads#20]
fix:

- [x] nomad UI skin is picked at the game start and not UEF as it currently is.
- [x] the bugs below

**Comment by speed2CZ** [comment]
it definitely doesn't pick it when you launch the game and if you switch to it, doesn't work correctly, throwing warning
```
WARNING: Error running console command UI_RotateSkin -: ...orged alliance\gamedata\mohodata.scd\lua\lazyvar.lua(92): You are attempting to set a LazyVar's evaluation function to nil, don't do that!
         stack traceback:
         	[C]: in function `error'
         	...orged alliance\gamedata\mohodata.scd\lua\lazyvar.lua(92): in function `Set'
         	c:\users\odstr\documents\github\fa\lua\ui\uiutil.lua(271): in function `SetCurrentSkin'
         	c:\users\odstr\documents\github\fa\lua\ui\uiutil.lua(339): in function <c:\users\odstr\documents\github\fa\lua\ui\uiutil.lua:304>

```

**Comment by CookieNoob** [comment]
in the lobby its fixed but ingame it will be UEF by default. Changing to the nomads skin in the first few seconds results in this error:

> INFO: attempting to set skin to: \000nomads
> WARNING: Error running console command UI_RotateSkin -: ...orged alliance\gamedata\mohodata.scd\lua\lazyvar.lua(86): attempt to call method `OnDirty' (a nil value)
>          stack traceback:
>          	...orged alliance\gamedata\mohodata.scd\lua\lazyvar.lua(86): in function `SetValue'
>          	...orged alliance\gamedata\mohodata.scd\lua\lazyvar.lua(97): in function `Set'
>          	e:\gits\fa\lua\ui\uiutil.lua(252): in function `SetCurrentSkin'
>          	e:\gits\fa\lua\ui\uiutil.lua(339): in function <e:\gits\fa\lua\ui\uiutil.lua:304>

however, swiching to the nomads skin after 20 ingame seconds (for me at least) yields no error and actually swiches to the working nomads UI.

**Comment by TheKeyBlue** [comment]
Could you maybe explain what you did? Cause i'm not sure what you mean.

**Comment by CookieNoob** [comment]
when you press ALT+ right/left arrow you can cycle through the skins. Its one of the few useful debug keys ^^
