### ISSUE TITLE
t3 static arty issues

### ISSUE THREAD

**Issue by CookieNoob** [CookieNoob/nomads#42]
targeting doesnt really work, it loses its target when tried to use in groundfire mode (shoot ground)
it also loses its target sometimes when used in normal attack mode (shoot unit)

killing an acu resulted in a lot of errors and no acu explosion (all acu models)

**Comment by TheKeyBlue** [comment]
> killing an acu resulted in a lot of errors and no acu explosion (all acu models)

is this issue about arty or acu?

**Comment by CookieNoob** [comment]
it is about arty, I just noticed it when I fired on acus... it happened with all units.
the veterancy system got changed and caused an error in the "OnArtilleryUnitKilledUnit" thus the script terminated there and never played the death animation.

**Comment by TheKeyBlue** [comment]
ah ok. Was unclear that you meant that the arty killed the acu.
Looked like title and description where unrelated.
