### ISSUE TITLE
cursor for intel probe missing

### ISSUE THREAD

**Issue by CookieNoob** [CookieNoob/nomads#46]
how to reproduce: upgrade intel probe and try to use it

**Comment by CookieNoob** [comment]
this is actually not an issue when using the nomads UI. Only for non-nomads UI skins this error occurs and then it doesnt prevent the intel probe to work

**Comment by Exotic-Retard** [comment]
wait so is it possible to have a non-nomads ui and use the probe? if so we may consider needing to fix this anyway.

**Comment by CookieNoob** [comment]
you can use the non-nomad skin if you use the debug keys to switch the skin ingame (ALT+arrow keys). Then it will spam some errors in the log but the probe works anyway.

I dont think we need to fix it
